# Generated by Django 2.2.3 on 2019-08-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='botes',
            new_name='votes',
        ),
    ]
